[topology]
# Sink listens on all interfaces (container friendly).
sink.sip_bind   = "0.0.0.0:5062"

# Choose one playout path (uncomment exactly one):
# 1) Play out via ALSA (change device/format if needed)
sink.aplay_cmd  = "aplay -f S16_LE -r 8000 -c 1 -t raw"
# 2) Or write to a file (useful on headless hosts)
# sink.aplay_cmd  = "tee /tmp/sink.pcm > /dev/null"

# Mixer accepts from Source on :5063 and dials the Sink
mixer.sip_bind   = "0.0.0.0:5063"
# Replace the IP below with your host/interface IP if different
mixer.sip_target = "sip:YOUR_HOST_IP:5062"

# Source dials the Mixer
source.sip_target = "sip:YOUR_HOST_IP:5063"
source.audio_file = "./assets/sample.mp3"

# Give the sink/mixer time to settle before first media
source.preroll_ms = 300
